# Generated by Django 2.1.5 on 2019-04-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='political_party',
            field=models.CharField(choices=[('democrat', 'democrat'), ('republican', 'republican'), ('libertarian', 'libertarian'), ('green', 'green'), ('independent', 'independent'), ('other', 'other')], default='independent', max_length=10),
        ),
    ]
