# Generated by Django 2.1.5 on 2019-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_political_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='political_party',
            field=models.CharField(choices=[('democrat', 'democrat'), ('republican', 'republican'), ('libertarian', 'libertarian'), ('green', 'green'), ('independent', 'independent'), ('other', 'other')], default='independent', max_length=20),
        ),
    ]
