# Generated by Django 2.1.5 on 2019-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190519_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='XX', max_length=2),
        ),
    ]
