
import React from 'react';


const AboutFeed = () =>  {
    
    const picture = 'https://bythepeople.s3.amazonaws.com/nycpicture.jpg';
    
    return (
        <div className="about-feed">

            <p> ByThePeople is a platform dedicated to bridging the gap between
                constituents and representatives by enabling voters to express
                opinions, socialize political views, and gather policy information
                in a simple, comprehensive manner, shifting the democratic process
                back into the hands of those that matter most, The People. We source 
                most of our data, including recent bills, 
                Congressperson biographical information, and voting records 
                from&nbsp;
            
                <a href='https://www.propublica.org' target="_blank">ProPublica</a>
            
                's API. This API in turn directly scrapes data from the&nbsp;

                <a href='https://www.congress.gov' target="_blank">Congress</a>

                &nbsp;website. Full bill text is usually unavailable until a couple 
                of days after introduction, but we scrape this ourselves from&nbsp;

                <a href='https://www.congress.gov' target="_blank">congress.gov</a>.
                <br></br>
                <br></br>
                Our polls are created by us, and for polls that are related to 
                specific bills, we do our best to be unbiased.
                <br></br>
                <br></br>
                Polls within our Recommended Polls feature are generated by 
                a proprietary algorithm based on polls you've interacted with 
                previously and are updated every page refresh.
            </p>

            <div className='about-feed-img-container'>
                <img
                    className='about-feed-img'
                    src={picture}
                >
                </img>
            </div>

        </div>
    );
}

export default AboutFeed

