# Generated by Django 2.1.5 on 2019-05-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('party', models.CharField(max_length=10)),
                ('in_office', models.BooleanField()),
                ('seniority', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('state', models.CharField(max_length=2)),
                ('senate_class', models.IntegerField()),
                ('votes_with_party_pct', models.FloatField()),
                ('chamber', models.CharField(max_length=1)),
            ],
        ),
    ]
