# Generated by Django 2.1.5 on 2019-05-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('party', models.CharField(max_length=10)),
                ('in_office', models.BooleanField()),
                ('seniority', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('state', models.CharField(max_length=2)),
                ('votes_with_party_pct', models.FloatField()),
                ('chamber', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
        migrations.CreateModel(
            name='HouseRep',
            fields=[
                ('district', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='representatives.BaseMember')),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('senate_class', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='representatives.BaseMember')),
            ],
        ),
    ]
