# Generated by Django 2.1.5 on 2019-05-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0002_auto_20190527_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserep',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member_house_rep', serialize=False, to='representatives.BaseMember'),
        ),
        migrations.AlterField(
            model_name='senator',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member_senator', serialize=False, to='representatives.BaseMember'),
        ),
    ]
