# Generated by Django 2.1.5 on 2019-09-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0003_auto_20190527_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemember',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
