# Generated by Django 2.1.5 on 2019-09-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0004_auto_20190922_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemember',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='basemember',
            name='last_updated',
        ),
    ]
