# Generated by Django 2.1.5 on 2019-10-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0006_auto_20190929_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberbillvotes',
            unique_together=set(),
        ),
    ]
