# Generated by Django 2.1.5 on 2019-10-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0007_auto_20191006_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemember',
            name='picture_uri',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
