# Generated by Django 2.1.5 on 2019-02-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(max_length=10)),
                ('bill_id', models.CharField(max_length=20)),
                ('api_uri', models.CharField(max_length=50)),
                ('legislative_day', models.CharField(max_length=10)),
                ('scheduled_at', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('bill_url', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
