# Generated by Django 2.1.5 on 2019-02-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0003_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='urlToImage',
        ),
    ]
