# Generated by Django 2.1.5 on 2019-02-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0005_auto_20190219_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='byThePeople.Poll'),
        ),
    ]
