# Generated by Django 2.1.5 on 2019-03-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0006_auto_20190223_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
