# Generated by Django 2.1.5 on 2019-04-20 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('byThePeople', '0008_auto_20190420_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polluservotes',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='polluservotes',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='polluservotes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='polluservotes',
            unique_together={('user', 'poll')},
        ),
    ]
