# Generated by Django 2.1.5 on 2019-04-25 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('byThePeople', '0009_auto_20190420_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='byThePeople.UpcomingBill')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
