# Generated by Django 2.1.5 on 2019-05-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0012_commentuserlikes_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentuserlikes',
            name='action',
            field=models.IntegerField(default=0),
        ),
    ]
