# Generated by Django 2.1.5 on 2019-05-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0013_auto_20190509_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingbill',
            name='polls',
            field=models.ManyToManyField(to='byThePeople.Poll'),
        ),
    ]
