# Generated by Django 2.1.5 on 2019-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0014_upcomingbill_polls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pk'], 'permissions': [('modify_poll', 'Can modify polls')]},
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='polls',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='headline',
            name='description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='api_uri',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='bill_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='bill_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='legislative_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='scheduled_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
