# Generated by Django 2.1.5 on 2019-05-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0015_auto_20190519_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pk']},
        ),
    ]
