# Generated by Django 2.1.5 on 2019-08-10 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0017_upcomingbill_related_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='polluservotes',
            name='time_voted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
