# Generated by Django 2.1.5 on 2019-09-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0018_polluservotes_time_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingbill',
            name='api_uri',
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='bill_url',
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='chamber',
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='legislative_day',
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='upcomingbill',
            name='url',
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='bill_slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='bill_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='bill_uri',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='committees',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='congressdotgov_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='enacted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='house_passage',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='introduced_date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='last_vote',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='latest_major_action',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='latest_major_action_date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='senate_passage',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='short_title',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='sponsor_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='title',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingbill',
            name='vetoed',
            field=models.BooleanField(null=True),
        ),
    ]
