# Generated by Django 2.1.5 on 2019-09-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0019_auto_20190919_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingbill',
            name='last_vote',
        ),
    ]
