# Generated by Django 2.1.5 on 2019-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0020_remove_upcomingbill_last_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='enacted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='house_passage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='senate_passage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='vetoed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
