# Generated by Django 2.1.5 on 2019-09-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0021_auto_20190919_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='short_title',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
