# Generated by Django 2.1.5 on 2019-10-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0022_auto_20190929_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingbill',
            name='id',
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='bill_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
