# Generated by Django 2.1.5 on 2019-10-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0023_auto_20191004_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingbill',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingbill',
            name='bill_id',
            field=models.CharField(max_length=100),
        ),
    ]
