# Generated by Django 2.1.5 on 2019-10-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byThePeople', '0024_auto_20191005_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingbill',
            name='bill_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
